language: node_js

node_js:
  - "8"

script: npm run test

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install: yarn

before_script:
  - npm run bootstrap

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov/bin/codecov

cache:
  yarn: true
  directories:
    - node_modules
