language: node_js

node_js:
  - "8"


script:
  - npm run test
  - if [[ $TRAVIS_COMMIT_MESSAGE == *"#benchmark"* ]]; then npm run benchmark ; fi;

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install: yarn install --frozen-lockfile

before_script:
  - npm run bootstrap

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov/bin/codecov

cache:
  yarn: true
  directories:
    - node_modules
