version: 2
jobs:
  flow:
    docker:
      - image: circleci/node:10.13.0-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v4-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v4-dependencies-
      - run: yarn install --pure-lockfile
      - run: yarn flow:check
      - run: yarn build
      - run: cd scripts/benchmarks && yarn build
      - store_artifacts:
          path: ~/repo/scripts/benchmarks/dist
      - save_cache:
          paths:
            - ~/.cache/yarn
            - node_modules
          key: v4-dependencies-{{ checksum "yarn.lock" }}

  test:
    docker:
      - image: circleci/node:10.13.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v4-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v4-dependencies-
      - run: yarn install --pure-lockfile
      - run:
          name: Jest Tests
          command: yarn coverage --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT: 'reports/junit/js-test-results.xml'
      - run: yarn codecov
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit

  test_dist:
    docker:
      - image: circleci/node:10.13.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v4-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v4-dependencies-
      - run: yarn install --pure-lockfile
      - run:
          name: Jest Tests
          command: yarn test:prod --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT: 'reports/junit/js-test-results.xml'

  lint_and_typescript:
    docker:
      - image: circleci/node:10.13.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v4-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v4-dependencies-
      - run: yarn install --pure-lockfile
      - run: yarn lint:check

workflows:
  version: 2
  build-and-test:
    jobs:
      - flow
      - test
      - test_dist
      - lint_and_typescript
