version: 2
jobs:
  flow:
    docker:
      - image: circleci/node:10.6.0-browser
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install --pure-lockfile
      - run: yarn flow
      - run: yarn build && cd scripts/benchmarks && yarn build && yarn run-benchmark && yarn run-benchmark
      - save_cache:
          paths:
            - ~/.cache/yarn
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

  test:
    docker:
      - image: circleci/node:10.6.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install --pure-lockfile
      - run: yarn coverage
      - run: yarn codecov
  test_dist:
    docker:
      - image: circleci/node:10.6.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install --pure-lockfile
      - run: yarn test:prod
  lint_and_typescript:
    docker:
      - image: circleci/node:10.6.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install --pure-lockfile
      - run: yarn lint:check
      - run: yarn test:typescript


workflows:
  version: 2
  build-and-test:
    jobs:
      - flow
      - test
      - test_dist
      - lint_and_typescript
